# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8323499b9687d632d34338b6d19ca45ab4a17cac615d7f69b6e9f2cdd474ebdd4155c230537e760baf76c0dbf8e3eb0aedfdd48ff0bc071082221fd9782b9b2

test:
  secret_key_base: dabf9f6426782ce609816c15d41dcd94b5a4092bf6606a10b93d329fb5f70250beaeac3cfadbd4e12327558c21c823a77f745c7206c7395e716c7684a2284b9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
